command:
  - streamlit
  - run
  - app.py
  - "--server.port"
  - "8501"
  - "--server.address"
  - "0.0.0.0"

env:
  - name: DATABRICKS_HOST
    description: Databricks workspace URL (auto-populated when deployed via DAB)
